use HOTEL_ALURA;
INSERT INTO USUARIOS (usuario, password) VALUES('admin', '21232f297a57a5a743894ae4a801fc3');
-- SELECT * FROM USUARIOS;
-- SELECT * FROM RESERVAS;
-- select * from huespedes;

-- ALTER TABLE HOTEL_ALURA.USUARIOS ADD COLUMN USUARIO VARCHAR(25) UNIQUE NOT NULL;

-- ALTER TABLE HOTEL_ALURA.USUARIOS DROP COLUMN EMAIL;

SELECT * FROM RESERVAS WHERE ID=11;

-- UPDATE HOTEL_ALURA.HUESPEDES
-- SET NOMBRE = ?, APELLIDO = ?, FECHA_NACIMIENTO=?, NACIONALIDAD=?, TELEFONO=?
-- WHERE ID=?;

-- DELETE FROM HOTEL_ALURA.RESERVAS WHERE ID=1;


commit;
